AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters: 
  SYSTEM:
    Description: system name
    Type: String
    Default: cfn-flow-test

  ENV:
    Description:  env type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  OriginDomainName:
    Description: dns name of origin endpoint
    Type: String

  RootDomainName:
    Type: String
  RootDomainHostedZoneId:
    Type: AWS::Route53::HostedZone::Id


Resources: 

  CdnCert:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Sub cdn.${SYSTEM}.${RootDomainName}
      DomainValidationOptions: 
        - 
          DomainName: !Sub cdn.${SYSTEM}.${RootDomainName}
          HostedZoneId: !Ref RootDomainHostedZoneId

      ValidationMethod: DNS

  Cdn:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        Aliases: 
          - !Sub cdn.${SYSTEM}.${RootDomainName}
        # CNAMEs: 
        #   - String
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          ResponseHeadersPolicyId: e61eb60c-9c35-4d20-a928-2b84e02af89c
          TargetOriginId: alb-origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: ""
        Enabled: true
        IPV6Enabled: false
        Origins: 
          - 
            CustomOriginConfig: 
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
            DomainName: !Ref OriginDomainName
            Id: alb-origin

        PriceClass: PriceClass_200
        ViewerCertificate: 
          AcmCertificateArn: !Ref CdnCert
          SslSupportMethod: sni-only


  CdnRecord:
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget: 
        DNSName: !GetAtt Cdn.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref RootDomainHostedZoneId
      Name: !Sub cdn.${SYSTEM}.${RootDomainName}
      Type: A

Outputs:
  CdnUrl:
    Description: url for cdn endpoint
    Value: !Sub https://cdn.${SYSTEM}.${RootDomainName}/
