AWSTemplateFormatVersion: 2010-09-09
Description: test template file
Parameters: 
  SYSTEM:
    Description: system name
    Type: String
    Default: cfn-flow-test

  ENV:
    Description:  env type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Mappings:
  CidrMap:
    ap-northeast-1:
      Vpc: 10.0.0.0/16
      PublicSubnet1: 10.0.0.0/24
      PublicSubnet2: 10.0.1.0/24
      PrivateSubnet1: 10.0.2.0/24
      PrivateSubnet2: 10.0.3.0/24
    ap-northeast-3:
      Vpc: 10.1.0.0/16
      PublicSubnet1: 10.1.0.0/24
      PublicSubnet2: 10.1.1.0/24
      PrivateSubnet1: 10.1.2.0/24
      PrivateSubnet2: 10.1.3.0/24
      

Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Fn::FindInMap:
          - CidrMap
          - !Ref AWS::Region
          - Vpc
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${SYSTEM}-${ENV}-vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - !GetAZs ''
      VpcId: !Ref VPC
      CidrBlock:
        Fn::FindInMap:
          - CidrMap
          - !Ref AWS::Region
          - PublicSubnet1

      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SYSTEM}-${ENV}-public-subnet-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - !GetAZs ''
      VpcId: !Ref VPC
      CidrBlock:
        Fn::FindInMap:
          - CidrMap
          - !Ref AWS::Region
          - PublicSubnet2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SYSTEM}-${ENV}-public-subnet-2
          
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - !GetAZs ''
      VpcId: !Ref VPC
      CidrBlock:
        Fn::FindInMap:
          - CidrMap
          - !Ref AWS::Region
          - PrivateSubnet1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${SYSTEM}-${ENV}-private-subnet-1
          
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - !GetAZs ''
      VpcId: !Ref VPC
      CidrBlock:
        Fn::FindInMap:
          - CidrMap
          - !Ref AWS::Region
          - PrivateSubnet2
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${SYSTEM}-${ENV}-private-subnet-2

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${SYSTEM}-${ENV}-igw
          
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  PublicRt:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${SYSTEM}-${ENV}-public-rt
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRt
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
  PublicRouteAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRt
  PublicRouteAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRt


Outputs:

  VpcId:
    Description: vpc id
    Value: !Ref VPC
    Export:
      Name: !Sub ${SYSTEM}-${ENV}-vpc
  PublicSubnetId1:
    Description: public subnet id 1
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${SYSTEM}-${ENV}-public-subnet-1
  PublicSubnetId2:
    Description: public subnet id 2
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${SYSTEM}-${ENV}-public-subnet-2

  PrivateSubnetId1:
    Description: private subnet id 1
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${SYSTEM}-${ENV}-private-subnet-1
  PrivateSubnetId2:
    Description: private subnet id 2
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${SYSTEM}-${ENV}-private-subnet-2
