version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cfn-flow-dev-api-backends"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l2w6x2engrnu"
s3_prefix = "cfn-flow-dev-api-backends"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "SolutionName=\"cfn-flow\" EnvName=\"dev\" UserPoolArn=\"arn:aws:cognito-idp:ap-northeast-1:382098889955:userpool/ap-northeast-1_NQ9m5lB7a\" ApiDomainName=\"api.cfn-flow.ht-burdock.com\" ApiHostedZoneId=\"Z039399416TTZBHG4C8OO\""
image_repositories = []
