Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: 2010-09-09
Description: ---
# Metadata: 

Parameters: 
  SolutionName:
    Type: String
    Default: cfn-flow
  EnvName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  UserPoolArn:
    Type: String


# Mappings: 

# Conditions: 

Resources:


  UtilLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./layers/utils/
      CompatibleRuntimes:
        - python3.9
      CompatibleArchitectures:
        - x86_64
      LayerName: !Sub ${SolutionName}-${EnvName}-util-layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9

  CfnUtilLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./layers/cfn_utils/
      CompatibleRuntimes:
        - python3.9
      CompatibleArchitectures:
        - x86_64
      LayerName: !Sub ${SolutionName}-${EnvName}-cfn-util-layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9


  TemplatesFunctionsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      # Policies:


  ListTemplates:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./functions/templates/
      Environment:
        Variables:
          DYNAMO_TEMPLATE_TABLE_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-templates-table
          DYNAMO_TEMPLATE_SUMMARY_TABLE_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-template-summaries-table
          S3_TEMPLATE_BUCKET_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-templates-bucket 
      EphemeralStorage:
        Size: 512
      # EventInvokeConfig: EventInvokeConfiguration
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY      
            RestApiId:  !Ref TemplatesApi
#             Auth:
 #              ApiKeyRequired: true
        GetApi:
          Type: Api
          Properties:
            Method: get
            Path: /templates
            RestApiId:  !Ref TemplatesApi
#             Auth:
 #              ApiKeyRequired: true
      FunctionName: !Sub ${SolutionName}-${EnvName}-templates-list-function
      Handler: list_templates.lambda_handler
      Layers:
        - !Ref UtilLayer
        # - !Ref CfnUtilLayer
      MemorySize: 1024
      PackageType: Zip
      # Policies: String | List | Map
      Role: !GetAtt TemplatesFunctionsRole.Arn
      # RolePath: String
      Runtime: python3.9
      Timeout: 60
      Tracing: Active

  PutTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./functions/templates/
      Environment:
        Variables:
          DYNAMO_TEMPLATE_TABLE_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-templates-table
          DYNAMO_TEMPLATE_SUMMARY_TABLE_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-template-summaries-table
          S3_TEMPLATE_BUCKET_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-templates-bucket 
      EphemeralStorage:
        Size: 512
      # EventInvokeConfig: EventInvokeConfiguration
      Events:
        PutApi:
          Type: Api
          Properties:
            Method: put
            Path: /templates/{templateName}
            RestApiId:  !Ref TemplatesApi
#             Auth:
 #              ApiKeyRequired: true
      FunctionName: !Sub ${SolutionName}-${EnvName}-templates-put-function
      Handler: put_template.lambda_handler
      Layers:
        - !Ref UtilLayer
        - !Ref CfnUtilLayer
      MemorySize: 1024
      PackageType: Zip
      # Policies: String | List | Map
      Role: !GetAtt TemplatesFunctionsRole.Arn
      # RolePath: String
      Runtime: python3.9
      Timeout: 60
      Tracing: Active


  GetTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./functions/templates/
      Environment:
        Variables:
          DYNAMO_TEMPLATE_TABLE_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-templates-table
          DYNAMO_TEMPLATE_SUMMARY_TABLE_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-template-summaries-table
          S3_TEMPLATE_BUCKET_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-templates-bucket 
      EphemeralStorage:
        Size: 512
      # EventInvokeConfig: EventInvokeConfiguration
      Events:
        GetApi:
          Type: Api
          Properties:
            Method: get
            Path: /templates/{templateName}/{sectionName}
            RestApiId:  !Ref TemplatesApi
#             Auth:
 #              ApiKeyRequired: true
      FunctionName: !Sub ${SolutionName}-${EnvName}-template-get-function
      Handler: get_template.lambda_handler
      Layers:
        - !Ref UtilLayer
      MemorySize: 1024
      PackageType: Zip
      # Policies: String | List | Map
      Role: !GetAtt TemplatesFunctionsRole.Arn
      # RolePath: String
      Runtime: python3.9
      Timeout: 60
      Tracing: Active


  DeleteTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./functions/templates/
      Environment:
        Variables:
          DYNAMO_TEMPLATE_TABLE_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-templates-table
          DYNAMO_TEMPLATE_SUMMARY_TABLE_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-template-summaries-table
          S3_TEMPLATE_BUCKET_NAME:
            Fn::ImportValue: !Sub ${SolutionName}-${EnvName}-templates-bucket 
      EphemeralStorage:
        Size: 512
      # EventInvokeConfig: EventInvokeConfiguration
      Events:
        GetApi:
          Type: Api
          Properties:
            Method: get
            Path: /templates/{templateName}
            RestApiId:  !Ref TemplatesApi
#             Auth:
 #              ApiKeyRequired: true
      FunctionName: !Sub ${SolutionName}-${EnvName}-template-delete-function
      Handler: delete_template.lambda_handler
      Layers:
        - !Ref UtilLayer
      MemorySize: 1024
      PackageType: Zip
      # Policies: String | List | Map
      Role: !GetAtt TemplatesFunctionsRole.Arn
      # RolePath: String
      Runtime: python3.9
      Timeout: 60
      Tracing: Active


  TemplatesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref EnvName
      Name: !Sub ${SolutionName}-${EnvName}-templates-api
      # BinaryMediaTypes:
        # - ""
      Cors:
        # AllowCredentials: true
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'OPTIONS,GET,PUT,POST,DELETE'"
        AllowOrigin: "'*'"

      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
