Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: 2010-09-09
Description: ---
# Metadata: 

Parameters: 
  SolutionName:
    Type: String
    Default: cfn-flow
  EnvName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

# Mappings: 

# Conditions: 

Resources:
  UtilLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: utils/
      CompatibleRuntimes:
        - python3.9
      CompatibleArchitectures:
        - x86_64
      LayerName: !Sub ${SolutionName}-${EnvName}-util-layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9

  CfnUtilLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: cfn_utils/
      CompatibleRuntimes:
        - python3.9
      CompatibleArchitectures:
        - x86_64
      LayerName: !Sub ${SolutionName}-${EnvName}-cfn-util-layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9

# Outputs: